on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    name: "Update Job"
    steps:
    - name: "Greeting step"
      uses: "abhishekr700/push-flock-notify@master"
      env:
        WEBHOOK: ${{ secrets.WEBHOOK }}